In [1]:
from __future__ import print_function
import torch as t

In [2]:
# 构建5*3的矩阵，未初始化，仅分配空间
x = t.Tensor(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
# 使用0-1均匀分布，随机初始化二维数组
x = t.rand(5, 3)
x

tensor([[0.6277, 0.5451, 0.3011],
        [0.7497, 0.6440, 0.8294],
        [0.0015, 0.2254, 0.8846],
        [0.3291, 0.9545, 0.9283],
        [0.8947, 0.6735, 0.0959]])

In [4]:
print(x.size()) # 查看x 的形状
x.size(0)

torch.Size([5, 3])


5

In [5]:
y = t.rand(5, 3)
# 加法的三种写法
print(x + y)
print(t.add(x, y))
result = t.Tensor(5, 3)
t.add(x, y, out=result)
print(result)

tensor([[1.6252, 1.2264, 0.8416],
        [0.8098, 1.0568, 1.0254],
        [0.7846, 0.5171, 1.0329],
        [1.2445, 1.6089, 1.1360],
        [1.8559, 1.3410, 0.1308]])
tensor([[1.6252, 1.2264, 0.8416],
        [0.8098, 1.0568, 1.0254],
        [0.7846, 0.5171, 1.0329],
        [1.2445, 1.6089, 1.1360],
        [1.8559, 1.3410, 0.1308]])
tensor([[1.6252, 1.2264, 0.8416],
        [0.8098, 1.0568, 1.0254],
        [0.7846, 0.5171, 1.0329],
        [1.2445, 1.6089, 1.1360],
        [1.8559, 1.3410, 0.1308]])


In [6]:
print(y)
y.add(x)
print(y)
y.add_(x)
print(y)

tensor([[0.9975, 0.6813, 0.5405],
        [0.0601, 0.4128, 0.1960],
        [0.7831, 0.2917, 0.1483],
        [0.9154, 0.6544, 0.2077],
        [0.9613, 0.6675, 0.0349]])
tensor([[0.9975, 0.6813, 0.5405],
        [0.0601, 0.4128, 0.1960],
        [0.7831, 0.2917, 0.1483],
        [0.9154, 0.6544, 0.2077],
        [0.9613, 0.6675, 0.0349]])
tensor([[1.6252, 1.2264, 0.8416],
        [0.8098, 1.0568, 1.0254],
        [0.7846, 0.5171, 1.0329],
        [1.2445, 1.6089, 1.1360],
        [1.8559, 1.3410, 0.1308]])


In [7]:
# numpy 与 Tensor 操作非常相近可以互相转换
a = t.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [8]:
b = a.numpy() # Tensor -> numpy ndarray
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [9]:
import numpy as np
a = np.ones(5)
b = t.from_numpy(a) # Numpy ndarray -> Tensor
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [10]:
b.add_(1)
print(a)
print(b) # 共享内存

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [32]:
# cuda 冲起来，把Tensor 转换为 GPU 的Tensor
if t.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    for i in range(100):
        x + y

In [37]:
import time, os
os.environ["CUDA_VISIBLE_DEVICES"]="1"
begin = time.time()
for i in range(1):
    x = t.rand(3733, 3733)
    y = t.rand(3733, 3733)
    z = t.Tensor(3733, 3733)
    
    x = x.cuda()
    y = y.cuda() 
    z = z.cuda()
    t.add(x, y, out=z)
end = time.time()
print(z)
print(end - begin)
begin = time.time()
for i in range(1):
    x = t.rand(3733, 3733)
    y = t.rand(3733, 3733)
    z = t.Tensor(3733, 3733)
    
    t.add(x, y, out=z)
end = time.time()
print(z)
print(end - begin)

tensor([[0.5808, 0.2759, 1.1902,  ..., 0.9314, 0.1514, 0.7891],
        [1.4628, 0.4667, 0.8837,  ..., 1.2996, 0.6492, 0.7419],
        [0.9709, 0.8504, 1.6131,  ..., 0.8998, 0.7174, 1.0065],
        ...,
        [1.1400, 0.6167, 1.4326,  ..., 0.8442, 0.9254, 1.5875],
        [0.6447, 1.0376, 0.5972,  ..., 0.0663, 0.7005, 0.9886],
        [1.0324, 1.2996, 0.9249,  ..., 1.4015, 1.1062, 0.9329]],
       device='cuda:0')
0.22742223739624023
tensor([[1.2660, 0.9225, 0.8124,  ..., 1.2673, 0.5347, 1.4447],
        [1.8577, 0.9658, 0.8759,  ..., 0.9360, 0.7457, 1.5035],
        [0.5502, 0.8400, 1.6228,  ..., 0.6780, 0.5728, 1.1842],
        ...,
        [0.9185, 0.3635, 1.0821,  ..., 1.5648, 0.7308, 0.6776],
        [1.5607, 0.7822, 1.2979,  ..., 0.7699, 1.2422, 0.9965],
        [1.1874, 1.6490, 1.3018,  ..., 1.3351, 0.9788, 1.0807]])
0.15854692459106445


In [39]:
from torch.autograd import Variable
# 使用 Tensor 新建一个 Variable
x = Variable(t.ones(2, 2), requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [40]:
y = x.sum()
y

tensor(4., grad_fn=<SumBackward0>)

In [41]:
y.grad_fn

In [42]:
y.backward()

In [44]:
# y = x.sum() = (x[0][0] + x[0][1] + x[1][0] + x[1][1])
# 每个梯度值为1
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [45]:
y.backward()
x.grad

tensor([[2., 2.],
        [2., 2.]])

In [46]:
y.backward()
x.grad

tensor([[3., 3.],
        [3., 3.]])

In [47]:
x.grad.data.zero_()

tensor([[0., 0.],
        [0., 0.]])

In [48]:
# Variable 与 Tensor 有近乎一致的接口，在实际使用中可以无缝切换。
x = Variable(t.ones(4, 5))
y = t.cos(x)
x_tensor_cos = t.cos(x.data)
print(y)
x_tensor_cos

tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]])


tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]])